//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define DIALOG_FONT 14, "Helvetica"

#define IDOK 1
#define IDCANCEL 2
#define IDI_ICON1 101
#define IDD_DIALOG_REASONUS_NATIVE 102
#define IDD_DIALOG_REASONUS_NATIVE_FUNCTIONS 103
#define IDD_DIALOG_REASONUS_NATIVE_FILTERS 104
#define IDD_DIALOG_REASONUS_NATIVE_PLUGIN_EDIT 105
#define IDD_DIALOG_REASONUS_NATIVE_V2 106
#define IDD_DIALOG_REASONUS_NATIVE_FUNCTIONS_V2 107
#define IDC_EDIT1 1000
#define IDC_BUTTON1 1001
#define IDC_LASTMSG 1002
#define IDC_CHECK1 1003
#define IDC_COMBO_MIDI_IN 1004
#define IDC_COMBO_MIDI_OUT 1005
#define IDC_STATIC 1006
#define IDC_GROUP_MIDI_DEVICES 1007
#define IDC_COMBO_SURFACE 1008
#define IDC_GROUP_SURFACE 1009
#define IDC_GROUP_SETTINGS 1010
#define IDC_CHECK_INIT_DIS_PLUGIN 1011
#define IDC_CHECK_INIT_SWAP_SHIFT 1012
#define IDC_CHECK_INIT_MUTE_MOMENTARY 1013
#define IDC_CHECK_INIT_TIME_CODE 1014
#define IDC_COMBO_INIT_TIME_CODE 1015
#define IDC_BUTTON_DOCUMENTTION 1041
#define IDC_VERSION 1042

//========================================================
// The functions dialog
//========================================================
#define IDC_EDIT_FUNCTION_1 1100
#define IDC_EDIT_FUNCTION_2 1101
#define IDC_EDIT_FUNCTION_3 1102
#define IDC_EDIT_FUNCTION_4 1103
#define IDC_EDIT_FUNCTION_5 1104
#define IDC_EDIT_FUNCTION_6 1105
#define IDC_EDIT_FUNCTION_7 1106
#define IDC_EDIT_FUNCTION_8 1107
#define IDC_BUTTON_ACTION_1 1116
#define IDC_BUTTON_ACTION_2 1117
#define IDC_BUTTON_ACTION_3 1118
#define IDC_BUTTON_ACTION_4 1119
#define IDC_BUTTON_ACTION_5 1120
#define IDC_BUTTON_ACTION_6 1121
#define IDC_BUTTON_ACTION_7 1122
#define IDC_BUTTON_ACTION_8 1123
#define IDC_BUTTON_INFO_1 1124
#define IDC_BUTTON_INFO_2 1125
#define IDC_BUTTON_INFO_3 1126
#define IDC_BUTTON_INFO_4 1127
#define IDC_BUTTON_INFO_5 1128
#define IDC_BUTTON_INFO_6 1129
#define IDC_BUTTON_INFO_7 1130
#define IDC_BUTTON_INFO_8 1131
#define IDC_GROUP_FUNCTION_INFO 1132
#define IDC_FUNCTION_INFO_ID 1133
#define IDC_FUNCTION_INFO_TYPE 1134
#define IDC_FUNCTION_INFO_NAME 1135
//========================================================
// The filters window controls
//========================================================
#define IDC_LIST_FILTERS 1200
#define IDC_BUTTON_ADD_FILTER 1201
#define IDC_BUTTON_REMOVE_FILTER 1202
#define IDC_BUTTON_FILTER_ITEM_UP 1203
#define IDC_BUTTON_FILTER_ITEM_DOWN 1204
#define IDC_EDIT_FILTER_NAME 1205
#define IDC_EDIT_FilterText 1206
#define IDC_BUTTON_ADD_TEXT 1207
#define IDC_LIST_FILTER_TEXT 1208
#define IDC_CHECK_SHOW_SIBBLINGS 1209
#define IDC_CHECK_SHOW_PARENTS 1210
#define IDC_CHECK_SHOW_CHILDREN 1211
#define IDC_CHECK_SHOW_TOP_LEVEL 1212
#define IDC_CHECK_MATCH_MULTIPLE 1213
#define IDC_GROUP_FILTERS 1214
#define IDC_BUTTON_REMOVE_TEXT 1215
//========================================================
// The plugin edit window controls
//========================================================
#define IDC_GROUP_PLUGIN_SELECT 1300
#define IDC_EDIT_PLUGIN_EDIT_SELECT_NAME 1301
#define IDC_EDIT_PLUGIN_EDIT_ORIG_NAME 1302
#define IDC_EDIT_PLUGIN_EDIT_SELECT_PARAM_ID 1303
#define IDC_EDIT_PLUGIN_EDIT_SELECT_NB_STEPS 1304
#define IDC_GROUP_PLUGIN_FADER 1305
#define IDC_EDIT_PLUGIN_EDIT_FADER_NAME 1306
#define IDC_EDIT_PLUGIN_EDIT_FADER_ORIG_NAME 1307
#define IDC_EDIT_PLUGIN_EDIT_FADER_PARAM_ID 1308

#define ID_QUIT 40000

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 103
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1004
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
